default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "password" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: iv_api_development

test:
  <<: *default
  database: iv_api_test

production:
  <<: *default
  database: iv_api_production
  username: iv_api
  password: <%= ENV["IV_API_DATABASE_PASSWORD"] %>

